// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:852191440674:web:077a6b3f49adb1fe313f7b',
    messagingSenderId: '852191440674',
    projectId: 'events-26bd4',
    authDomain: 'events-26bd4.firebaseapp.com',
    storageBucket: 'events-26bd4.firebasestorage.app',
    measurementId: 'G-EKFW3QNXWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:852191440674:android:af2303f45fc66d4e313f7b',
    messagingSenderId: '852191440674',
    projectId: 'events-26bd4',
    storageBucket: 'events-26bd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:852191440674:ios:70b6e99c074b4788313f7b',
    messagingSenderId: '852191440674',
    projectId: 'events-26bd4',
    storageBucket: 'events-26bd4.firebasestorage.app',
    iosBundleId: 'com.example.elPasoEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:852191440674:ios:70b6e99c074b4788313f7b',
    messagingSenderId: '852191440674',
    projectId: 'events-26bd4',
    storageBucket: 'events-26bd4.firebasestorage.app',
    iosBundleId: 'com.example.elPasoEvents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:852191440674:web:460bfabbac622903313f7b',
    messagingSenderId: '852191440674',
    projectId: 'events-26bd4',
    authDomain: 'events-26bd4.firebaseapp.com',
    storageBucket: 'events-26bd4.firebasestorage.app',
    measurementId: 'G-P618F37Y75',
  );
}
